ministryofjustice/correspondence_tool_public

Dockerfile
Dockerfile.development
docker-compose.yml

To get this working you you have to have docker installed and have docker-machine running
then run the following commands.
```
$ docker-compose build
$ docker-compose up
```

Add docker for local development and production

---

Gemfile
Gemfile.lock
config/application.rb

- Add faker and factory girl for use in testing
- Prevent factory girl from automatically creating fixtures, for now

Add faker and factory girl

---

config/application.rb

- I don't think we need this right now

active record not used

---

README.md

- How to setup Docker for local development

Initial details for readme

---

Gemfile
Gemfile.lock

Configure application to be able to deploy to heroku

Add heroku

---

Gemfile
Gemfile.lock
app/views/correspondence/new.html.slim
config/application.rb
spec/features/send_correspondence_spec.rb

- standard and most basic implementation of displaying error messages at the top of the form
- default messages with GOVUK styled error messages

basic implementation of error messages

---

app/controllers/correspondence_controller.rb
app/mailers/correspondence_mailer.rb
app/models/correspondence.rb
app/views/correspondence/new.html.slim
app/views/correspondence_mailer/new_correspondence.html.slim
config/settings.yml
spec/controllers/correspondence_controller_spec.rb
spec/factories/correspondence.rb
spec/mailers/correspondence_mailer_spec.rb
spec/models/correspondence_spec.rb

- Topics makes more sense to me than sub_types
- Minor refactor to change this
- Tested locally and all good

topics makes more sense than sub_types

---

config/initializers/sidekiq.rb
config/sidekiq.yml

- limit the number of connections to redis

Too many connections

---

app/mailers/correspondence_mailer.rb
spec/mailers/correspondence_mailer_spec.rb
spec/models/correspondence_spec.rb

- use ENV vars for now
- only two vars required
- FREEDOM_OF_INFORMATION_EMAIL
- TREAT_OFFICIAL_EMAIL

grab appropriate TO address from env

---

config/settings.yml

- We don't know that these options will be dealt with differently, so let's stick them all together on one line for now.
- Also added Probation

move other etc to one line

---

app/models/correspondence.rb
app/views/correspondence/new.html.slim

to prevent selection by default

add blank option to drop downs

---

app/views/correspondence/new.html.slim
config/locales/en.yml
spec/features/send_correspondence_spec.rb

- Refactor the web form view
- Adds some hint text about email address

Clean up the public web form view.

---

config/settings.yml

- change to order of list as per request from DACU
- change from treat official to general enquiries as per request from MG

change order and copy for type list

---

app/views/layouts/application.html.slim

Fix indents that were breaking the GA scripts from loading

---

app/assets/stylesheets/moj/_typography.scss
app/controllers/correspondence_controller.rb
app/views/correspondence/start.html.slim
app/views/layouts/_header.html.slim
config/routes.rb
spec/controllers/correspondence_controller_spec.rb

- Adds new service start page
- Styles headings correctly.

Service Start page

---

.rubocop.yml
Gemfile
Gemfile.lock
Guardfile

- precursory to continuing development on this code
- enable use of binding.pry for debugging
- use Guard for Rubocop

Pry and rubocop

---

app/controllers/correspondence_controller.rb
config/initializers/correspondence_logger.rb
spec/controllers/correspondence_controller_spec.rb
spec/spec_helper.rb

https://trello.com/c/Pwj2uP6n/227-5-log-correspondence-for-research-ask-tool
- Add tests to Misha's quick implementation of logging
- Refactor logging to separate logging code from #create action code in the correspondence_controller

REVIEW ME PLEASE - Logging refactor - ticket 227

---

Gemfile
Gemfile.lock
app/models/correspondence.rb
spec/controllers/correspondence_controller_spec.rb
spec/models/correspondence_spec.rb
spec/rails_helper.rb

https://trello.com/c/J4RP5Rwh/143-better-validations-both-in-public-and-staff-app
I've also done a little refactoring here, in the initial commits, to implement shoulda matchers and break up some long lines.

143 better validations

---

app/controllers/feedback_controller.rb
app/jobs/email_feedback_job.rb
app/mailers/feedback_mailer.rb
app/models/feedback.rb
app/views/correspondence/confirmation.html.slim
app/views/feedback/new.html.slim
app/views/feedback_mailer/new_feedback.html.slim
config/initializers/feedback_logger.rb
config/initializers/inflections.rb
config/locales/en.yml
config/routes.rb
config/settings.yml
spec/controllers/feedback_controller_spec.rb
spec/factories/feedback.rb
spec/features/send_feedback_spec.rb
spec/jobs/email_feedback_job_spec.rb
spec/mailers/feedback_mailer_spec.rb
spec/mailers/previews/feedback_mailer_preview.rb
spec/models/feedback_spec.rb

There is now a feedback link to the feedback link
once they have submitted their question.
It will email feedback to a google group email for staff and the team
to review. It will also be logged in a log file which will be in JSON
format.
TODO: Add the feedback.log to Kabana to review the data being submitted.
https://dsdmoj.atlassian.net/browse/CT-82
https://dsdmoj.atlassian.net/browse/CT-83
https://dsdmoj.atlassian.net/browse/CT-84
https://dsdmoj.atlassian.net/browse/CT-86
https://dsdmoj.atlassian.net/browse/CT-87

CT-82  Create and implement feedback page

---

app/mailers/correspondence_mailer.rb
app/views/correspondence_mailer/new_correspondence.html.slim
spec/mailers/correspondence_mailer_spec.rb

https://dsdmoj.atlassian.net/browse/CT-129

CT-129 Humanize user selected values in the email

---

Gemfile
Gemfile.lock
app/views/correspondence/confirmation.html.slim
app/views/correspondence/new.html.slim
app/views/feedback/new.html.slim
app/views/layouts/_phase_banner.html.slim
app/views/layouts/application.html.slim
config/i18n-tasks.yml
config/locales/en.yml
spec/i18n_spec.rb

https://dsdmoj.atlassian.net/browse/CT-48
All the views strings have an entry in i18n except the email templates which ware sent to staff and need to be in english only

Ct-48 i18n all the strings

---

Gemfile
Gemfile.lock
config/environments/production.rb

CT-168 format logs for logstash

---

public/500-nginx.html
public/500-redis-down.html

- Andy requested that we also include the phone number on these pages.
- This required some of the existing copy to change.

Include all alternative routes on 500 page

---

app/controllers/feedback_controller.rb
app/mailers/feedback_mailer.rb
app/models/feedback.rb
app/views/feedback/new.html.slim
app/views/feedback_mailer/new_feedback.html.slim
config/locales/en.yml
config/settings.yml
spec/controllers/feedback_controller_spec.rb
spec/factories/feedback.rb
spec/features/send_feedback_spec.rb
spec/mailers/feedback_mailer_spec.rb
spec/models/feedback_spec.rb

https://dsdmoj.atlassian.net/browse/CT-167
The feedback form was being used to give feedback on things beyond the digital service we are building.
@kelliematheson may wish to make some changes to the page before this gets merged.
UPDATE: @kelliematheson has approved the new error messages

CT-167 Update feedback to encourage intended use

---

app/views/feedback/new.html.slim

https://dsdmoj.atlassian.net/browse/CT-258
- Feedback text area bigger 
- cleaned up the markup

CT-258 Make the text area bigger

---

app/assets/stylesheets/moj/_typography.scss
app/controllers/correspondence_controller.rb
app/views/correspondence/start.html.slim
config/locales/en.yml
config/routes.rb
spec/features/send_correspondence_spec.rb

https://dsdmoj.atlassian.net/browse/CT-256
What we need on the page:
- how long a response will take
- how to find out about court facilities; link to court finder
- who to contact if they're already involve in a case
Acceptance criteria:
- view is created as per design
- "start now" button links to the existing web form
I added a start page to the service. I also added a new GA event
to capture 'clicks' to Find a court/tribunal service so we can see
whether people are finding that useful by directing them
there #self-service

CT-256 Add a start page

---

app/views/correspondence/new.html.slim
config/locales/en.yml
spec/features/send_correspondence_spec.rb

https://dsdmoj.atlassian.net/browse/CT-257
- Added Advice Copy/markup to the locale file
- Added 'rows' html attribute to the text area

CT-257 - Grow message box and add advice copy

---

smoketest.rb

Fixes smoke tests for the start-page change.

CT-256 Fix smoke tests

---

smoketest.rb

Whoops. Forgot to update the smoketest.

CT-266 Update smoketest for topic text field

---

.eslintrc
Gemfile
Gemfile.lock
app/assets/javascripts/application.js
app/views/layouts/_phase_banner.html.slim

https://dsdmoj.atlassian.net/browse/CT-269
- Updated the GOVUK elements in the Gemfile
- Checked non-js/js version of the new radio button styles
- Checked the GOVUK blue was applied to all phase banners on the service

CT-269 Update GOVUK elements

---

app/views/correspondence/confirmation.html.slim
app/views/correspondence/new.html.slim
app/views/correspondence/start.html.slim
app/views/feedback/confirmation.html.slim
app/views/feedback/new.html.slim
config/locales/en.yml

https://dsdmoj.atlassian.net/browse/CT-270
For SEO and accessibility, all pages should have a unique page title.
https://www.w3.org/TR/WCAG20/#navigation-mechanisms-title
https://www.w3.org/TR/WCAG-TECHS/G88.html

CT-270 Page titles for each page of the service

---

Gemfile
Gemfile.lock

https://dsdmoj.atlassian.net/browse/CT-449
I've created a PR for the Answer Tool https://github.com/ministryofjustice/correspondence_tool_staff/pull/98

CT-449 Update GOVUK Form Builder gem

---

Gemfile
Gemfile.lock
app/assets/stylesheets/moj/_layout.scss
app/assets/stylesheets/moj/_typography.scss
app/views/correspondence/start.html.slim
config/locales/en.yml
spec/features/send_correspondence_spec.rb
spec/rails_helper.rb
spec/support/site_prism/pages/correspondence/start_page.rb

https://dsdmoj.atlassian.net/browse/CT-425
- Add Site Prism for feature testing
- Implement new designs/Copy for the start page

CT-425 Update start page

---

app/models/correspondence.rb
config/settings.yml
spec/models/correspondence_spec.rb

https://dsdmoj.atlassian.net/browse/CT-494
Limit the message to 5000 characters. There will be another ticket to  show a counter on the page for the user. This is purely a change to the model to add validations.

CT-494 Limit message to 5000 characters (Backend)

---

app/assets/javascripts/modules/CharacterCount.js
app/assets/stylesheets/application.css.scss
app/assets/stylesheets/moj/_typography.scss
app/views/correspondence/_contact_form.html.slim
spec/features/send_correspondence_spec.rb
spec/site_prism/pages/correspondence/search_page.rb

https://dsdmoj.atlassian.net/browse/CT-432
This adds a js character counter to the search page
so that users can see how many characters have been
entered for the message.

CT-432 Add character counter

---

Gemfile
Gemfile.lock
app/services/gov_uk_search_api/client.rb
app/views/correspondence/search.html.slim
config/brakeman.ignore
spec/services/gov_uk_search_api/client_spec.rb

https://dsdmoj.atlassian.net/browse/CT-508
This implements a basic snowball stop list of words to
filter to. It takes the original topic and removes the stop words.
We are using a gem called stoplist-filter which has its own list of
stops words that can be extended. It also has locales support should
the service need to be translated into other languages.

CT-508 Improve GOVUK Search API call

---

app/assets/javascripts/modules/CharacterCount.js
spec/features/send_correspondence_spec.rb

https://dsdmoj.atlassian.net/browse/CT-560
I fixed this by triggering the keyup event which would
updating the character as if the user had manually entered
in some text.

CT-560 Character count not updating on page reload

---

app/views/correspondence/topic.html.slim
config/locales/en.yml
spec/site_prism/pages/correspondence/topic_page.rb

https://dsdmoj.atlassian.net/browse/CT-522
"Send" button on the topic page should read as "Continue"

CT-522 Change topic "Send" copy to "Continue"

---

config/locales/en.yml
spec/features/send_correspondence_spec.rb

As spotted during the demo. Oops!

Fix linik typo

---

app/controllers/correspondence_controller.rb
app/views/correspondence/_contact_form.html.slim
app/views/correspondence/t_and_c.html.slim
config/locales/en.yml
config/routes.rb
spec/features/send_correspondence_spec.rb
spec/views/correspondence/t_and_c_html_slim_spec.rb

**CT-1726 Create the Terms and conditions and privacy policy page for the Ask tool**
A new page added with content detailing how user data is being used and stored in accordance with the General Data Protection Regulation (GDPR)

Ct 1726 gdpr policy page

---

config/kubernetes/production/ingress.yaml
config/kubernetes/production/secrets.yaml
config/kubernetes/production/service.yaml

This is just part of setting up a namespace for Prod. I will try starting with Prod for a change so can delete bits for others. Resources etc separate tasks

CT-2794 setup namespace for prod

---

.gitattributes

Approved in separate PR, but had to rebase and cherry pick only relevant commits for develop.

CT-2824 Add Git Crypt

---

config/kubernetes/production/configmap.yaml

(Not deployed yet - can merge and then deploy)

Change to use real emails for prod in kubes config env vars

---

.circleci/config.yml

CircleCI project created under the MOJ organisation, and added config from CTS as a starting point. Lots potentially to be simplified but it's running and passing so I'm pretty happy :)
Have turned off code climate and travis for branch protection on develop and master here in settings
https://github.com/ministryofjustice/correspondence_tool_public/settings/branches
Disabling the web hook for CodeClimate - previous settings as below
https://github.com/ministryofjustice/correspondence_tool_public/settings/hooks/15354693

Add basic circle ci setup

---

app/controllers/pages_controller.rb
app/views/layouts/application.html.slim
app/views/pages/accessibility.html.slim
config/locales/en.yml
config/routes.rb
pull_request_template.md
spec/controllers/pages_controller_spec.rb
spec/views/pages/accessibility.html.slim_spec.rb

Adding new static page for the accessibility statement. Also adding PR template
Pardon me I guess because a template has been added maybe it's not here yet. Anyway, checks passed and shown to Ajiri. And demoed (already). 
You can view this by going to Contact MOJ and clicking on Accessibility in the footer.

CT-3011 Add accessibility statement

---

app/views/pages/accessibility.html.slim

Reduce size of intro paragraph for accessibility page - follow up PR for CT-3011
Related PR: https://github.com/ministryofjustice/correspondence_tool_public/pull/304
old:
new:
Ticket: https://dsdmoj.atlassian.net/browse/CT-3011
n/a
Click on accessibility in footer and check first paragraph size, should match others

CT-3011 reduce font size for intro as fedback

---

.circleci/config.yml

When someone deploys using Circle CI show the username in Slack
Before:
After:
https://dsdmoj.atlassian.net/browse/CT-3245
n/aa
Deploy a build on circle CI then check slack to check if your Github username is shown in the deploy message

CT-3245 Show username when deploying in slack

---

.circleci/config.yml
config/pipeline/aws_ecr_scan_results.py

Automate security scanning for docker image and use Cloud Platform image for deployment. Same as Track a Query -https://github.com/ministryofjustice/correspondence_tool_staff/pull/1484/files
Can be seen working here: https://development.contact-moj.service.justice.gov.uk/
https://dsdmoj.atlassian.net/browse/CT-3541
requires test of deployment as it's fully changed
Ensure deployment works and regression test site

CT-3541 automate scanning and upgrade deployment image

---

.circleci/config.yml
build.sh
config/kubernetes/production/cronjob-delete-old-ecr-images.yaml
deploy.sh

Updates refs from master to main
[CT-3623](https://dsdmoj.atlassian.net/browse/CT-3623)

CT-3623 update refs for master to main

---

config/kubernetes/development/deployment.yaml
config/kubernetes/production/deployment.yaml
config/kubernetes/staging/deployment.yaml

Dry out env vars - remove secrets for app-secrets from deployment files, and reference the secrets object instead
https://dsdmoj.atlassian.net/browse/CT-3556
test each env
basic regression

CT-3556 dry out env vars

---

app/views/pages/accessibility.html.slim

Update team Email on Accessibility statement 
old:
new:
n/a
Check Email address on Accessibility statement - it should be the only place with that email

CT-3747 Change Email address on Accessibliity statement

---

app/views/pages/accessibility.html.slim

Use new email address for contact on Accessibility statement
Old:
New:
https://dsdmoj.atlassian.net/browse/CT-3747
n/a
Check Email address on Accessibility statement

CT-3747 Change Email address on Accessiblity statement

---

config/kubernetes/development/ingress-live.yaml
config/kubernetes/development/ingress.yaml
deploy.sh

Send all traffic to Live cluster for Contact MOJ and test this worked. This should have been done some time ago but wasn't sure how to test, but now document has been updated with testing instructions.
(old)

Send all traffic to live

---

config/kubernetes/production/ingress-live.yaml
config/kubernetes/staging/ingress.yaml
deploy.sh

Live1 to Live migration  - for EKS
https://dsdmoj.atlassian.net/browse/CT-4044
Needs to be merged and deployed to prod - if it fails - create new PR to fix
It will not affect the App on live1
push through Circle CI and deploy to dev and staging first. If all good then merge and deploy to prod.

Ct 4044 prod live1 to live migration

---

config/kubernetes/production/ingress-live.yaml
config/kubernetes/production/ingress.yaml

Traffic is already redirected to live but needs to be on the repo

CT-3919 Redirect traffic to live for production

---

.circleci/config.yml
build.sh

Just change name of profile to be more accurate for reader

remove live-1 reference for reader

---

config/kubernetes/development/ingress-live.yaml
config/kubernetes/production/ingress-live.yaml
config/kubernetes/staging/ingress-live.yaml

Adds default modsecurity to the application

Add default modsecurity

---

app/views/layouts/application.html.slim

Remove phase banner
before
after:
https://dsdmoj.atlassian.net/browse/CT-4186
view homepage

CT-4186 hide phase banner

---

config/kubernetes/development/ingress-live.yaml
config/kubernetes/production/ingress-live.yaml
config/kubernetes/staging/ingress-live.yaml

Reverts ministryofjustice/correspondence_tool_public#570

Revert "Add default modsecurity"

---

app/assets/javascripts/modules/ShowHideContent.js

Fix contact form for chrome latest

---

config/kubernetes/development/ingress-live.yaml
config/kubernetes/production/ingress-live.yaml
config/kubernetes/staging/ingress-live.yaml

Cdpt 273 ingress update

---

README.md
app/assets/javascripts/modules/LoadTime.js
app/views/layouts/application.html.slim
config/application.rb
config/kubernetes/development/configmap.yaml
config/kubernetes/production/configmap.yaml
config/kubernetes/staging/configmap.yaml
config/settings.yml
public/400.html
public/401.html
public/403.html
public/404.html
public/405.html
public/406.html
public/408.html
public/411.html
public/413.html
public/415.html
public/416.html
public/422.html
public/423.html
public/424.html
public/500-redis-down.html
public/500.html
public/501.html
public/504.html
public/nginx/500.html
public/nginx/505.html

Upgrade to GA4, keep GA3 running, use GTM
https://dsdmoj.atlassian.net/browse/CDPT-212

CDPT-212 Setup GA4

---

app/views/pages/accessibility.html.slim

Update date for last updated on Acc statement
https://dsdmoj.atlassian.net/browse/CDPT-116

CDPT-116 fix date on Acc statement

---

.circleci/config.yml

remove redundant code around gitcrypt
CDPT-46

CDPT-466 remove redundant code

---

.circleci/config.yml

Connects to the AWS ECR using short lived credentials.
Also moved the vulnerabilities scan into a separate job as it needs a docker image with python installed.

CDPT-762 Use short lived credentials

---

.circleci/config.yml
app/controllers/heartbeat_controller.rb
spec/controllers/heartbeat_controller_spec.rb

Adds in ENV vars to be shown on /ping page.

CDPT-814 Pass env vars to docker image and fix build tag

---

.circleci/config.yml
Gemfile

Add Brakeman static vulnerability scanner to CircleCI build
https://dsdmoj.atlassian.net/jira/software/c/projects/CDPT/boards/1152?modal=detail&selectedIssue=CDPT-871

Add Brakeman to CI build

---

.circleci/config.yml

Replace deprecated image

---

app/controllers/heartbeat_controller.rb
config/kubernetes/development/ingress-live.yaml
config/kubernetes/production/ingress-live.yaml
config/kubernetes/staging/ingress-live.yaml
spec/controllers/heartbeat_controller_spec.rb

Use 500 status when healthcheck fails as that should render from application.
Remove config to try to render 503 in-app as it doesn't work

Change healthcheck error status

---

Gemfile.lock

Re-adds ruby as platform and adds missing gems to lock file

Resolve bundler issues

---

app/javascript/modules/CharacterCount.js

Fix a small bug where we weren't checking for the character count, which was creating an error with the JS on pages where it didn't exist.
N/A
https://dsdmoj.atlassian.net/browse/CDPT-2500
Can go straight to main
I have regression tested this manually and see no regression.
- Visit the homepage and open dev tools, console
- Observe no error
- Navigate through the remaining pages, observe there are no console errors
- Observe character count works as expected

CDPT-2500: Check for presence of character count to fix JS bug

---

app/controllers/cookies_controller.rb
app/views/cookies/show.html.erb
app/views/layouts/_cookie_banner.html.erb
app/views/layouts/_cookie_banner_confirmation.html.erb
app/views/layouts/application.html.erb
config/locales/en.yml
config/routes.rb
spec/features/cookie_page_spec.rb

Add cookie page to Contact Moj.
https://dsdmoj.atlassian.net/browse/CDPT-2450
To be merged into cookie banner work and deployed together.
- Visit the cookies page from the cookie banner and the app footer
- Observe
- Change cookie preferences via cookie page form
- Observe the cookie updates correctly in the dev tools and observe cookie confirmation/flash success notification
-

CDPT-2450: Add cookie page

---

.github/workflows/deploy.yml

Fix webhook env - checked other repos and all others look correct.
https://dsdmoj.atlassian.net/browse/CDPT-2507

CDPT-2507: Fix webhook

---

app/views/correspondence/start.html.erb

Update text before bullet list

Use paragraph and add colon for lead-in text

---

Gemfile
Gemfile.lock
app/assets/stylesheets/application.css.scss
app/views/layouts/application.html.erb
package.json
yarn.lock

Update GOV header component with the new component.
**Before:**
**After:**
https://dsdmoj.atlassian.net/browse/CDPT-2834

CDPT-2834: Update GOV.UK header

---

config/kubernetes/development/configmap.yaml
config/kubernetes/staging/configmap.yaml

For Dev and Staging environments, emails currently get submitted to: contact-moj-test@digital.justice.gov.uk.
This needs to change to: ContactMOJTest-gg@justice.gov.uk.
N/A
https://dsdmoj.atlassian.net/browse/CDPT-2688
N/A
Please submit test contact questions.

CDPT-2688 Updated test email address.
