ministryofjustice/correspondence_tool_public

Gemfile, Gemfile.lock, spec/rails_helper.rb, spec/spec_helper.rb
- add capybara/rspec for integration testing
- config
- no need for cucumber since we're not writing acceptance tests with stakeholders present
=> add capybara rspec and config

app/models/correspondence.rb, spec/models/correspondence_spec.rb
- blank is not the same as mismatching
- validate for both
=> email confirmation cannot be blank

app/assets/images/icons/tick-white.svg, app/assets/stylesheets/moj/_typography.scss, app/views/correspondence/confirmation.html.slim, spec/features/send_correspondence_spec.rb
- Add some basic eye-candy to the confirmation page
- Adds a means for users to return to the home page
=> Add some initial styling to the confirmation page 

.gitignore, Gemfile, Gemfile.lock, Procfile, app/controllers/correspondence_controller.rb, app/jobs/email_correspondence_job.rb, config/environments/development.rb, config/environments/production.rb, config/environments/test.rb, config/sidekiq.yml, spec/controllers/correspondence_controller_spec.rb, spec/jobs/email_correspondence_job_spec.rb
- send emails out of process
- use Sidekiq for now
- YAML.dump is required because models can only be used if they're persisted
- using foreman to start both redis and Sidekiq
@jaikoo : please can you take a quick look at this too?
=> email out of process with sidekiq

config/sidekiq.yml
On the free heroku redis instance we can only support a max of 20 connections, when previously the limit was set to 25. This fix should stop the max connection limit reached redis errors.
=> reduce redis concurrency to 20

.env.example, app/views/correspondence/new.html.slim, config/settings.yml, spec/controllers/correspondence_controller_spec.rb, spec/factories/correspondence.rb, spec/features/send_correspondence_spec.rb
- format type and topic to snakecase
- type will be used to select the correct internal email address, as in ENV['type_of_correspondence']
- topic changed for consistency
- changed to collection_select so that we can format the items for human readability in an elegant way
=> Format type and topic

Gemfile, Gemfile.lock, app/assets/javascripts/application.js
- <a> were behaving oddly, submit an invalid form and then click on the summary error messages at the top. It should take you to the invalid field.
=> Removed turbolinks so <a> work as expected

spec/controllers/correspondence_controller_spec.rb
- two tests were failing intermittently (~1 in 100)
- cause: Faker::Lorem.pragraph[1] returns the second character from #paragraph, which can sometimes be a space if, for example, the paragraph starts with 'A' (i.e. any single character word).  This caused the message validation to fail and our test expectation for posting to #create was not met.
- solution: Faker::Lorem.paragraph(1) returns one whole sentence.  Validation now OK.
=> use entire line from Faker::Lorem.paragraph

app/views/layouts/_flashes.html.slim
- we're not using them yet so the bug went unnoticed
- cause: syntax error
=> fix syntax errors in _flashes

Gemfile, Gemfile.lock
I removed the Global instance which was added by JC https://github.com/ministryofjustice/correspondence_tool_public/pull/55/files#diff-8b7db4d5cc4b8f6dc8feb7030baa2478R26
I dont think we use foreman in production only for dev env
=> 254 - Remove duplication of 'foreman' gem in the Gemfile

Gemfile
Fixes the error caused in #65. Foreman is actually used in production https://github.com/ministryofjustice/correspondence_tool_public/blob/develop/Dockerfile#L16
=> Foreman is required for both dev and production

app/controllers/correspondence_controller.rb, app/models/correspondence.rb, app/views/correspondence/new.html.slim, config/locales/en.yml, spec/controllers/correspondence_controller_spec.rb, spec/factories/correspondence.rb, spec/features/send_correspondence_spec.rb, spec/models/correspondence_spec.rb
https://trello.com/c/AKVmTzV3/252-add-the-confirmation-email-field-back-into-the-ask-tool-form-and-make-sure-the-label-reads-confirm-email-1
- Required until we have a page that confirms all inputs prior to submission
=> First iteration requires email_confirmation

app/views/correspondence/confirmation.html.slim
The business were concerned about mentioning 20 working days on the
confirmation page when it may be less or potentially more. This
would also reduce the users confidence in getting a timely reply.
https://dsdmoj.atlassian.net/browse/CT-115
=> CT-115 Managing customer expectations

app/assets/stylesheets/moj/_govuk_overrides.scss, app/views/layouts/_phase_banner.html.slim
The phase banner content has been updated and styling hack was removed.
This is because we have passed alpha stage.
https://dsdmoj.atlassian.net/browse/CT-76
=> 248 Replace 'Development' with 'ALPHA on the phase banner'

app/models/correspondence.rb
https://dsdmoj.atlassian.net/browse/CT-73
- Error messages shown at the top of the form should be in the same order as the form fields appear below.
- Email format validation should only be applied if the email field is not blank
=> Order of validations == order of errors on page

app/views/layouts/application.html.slim
https://dsdmoj.atlassian.net/browse/CT-75
This line is https://github.com/alphagov/govuk_template/blob/master/source/views/layouts/govuk_template.html.erb#L56 in govuk template that affects the linking
=> CT-75 Link the logo top left to gov.uk page

config/environments/development.rb, config/environments/production.rb, config/environments/test.rb
https://dsdmoj.atlassian.net/browse/CT-130
Emails were not displaying the images.
- They were pointing to the old heroku instance which was renamed
and we looking to remove shortly.
- Added a new system environment variable to store the domain that
will be added to the urls that the mailer produces.
=> CT-130 #peer-review Add correct domain to urls

app/controllers/feedback_controller.rb, app/jobs/email_feedback_job.rb, app/models/feedback.rb, config/initializers/feedback_logger.rb, db/migrate/20161013090839_create_feedback.rb, db/schema.rb, spec/controllers/feedback_controller_spec.rb, spec/jobs/email_feedback_job_spec.rb, spec/models/feedback_spec.rb
https://dsdmoj.atlassian.net/browse/CT-161
- feedback was being saved to logfile
- this was going to be complicated to access and maintain
- save to DB instead
Next
- Implement an API to display feedback ratings on Geckoboard
- Ticket created: https://dsdmoj.atlassian.net/browse/CT-162
=> Save Feedback to DB, not logfile

app/controllers/correspondence_controller.rb, app/jobs/email_correspondence_job.rb, spec/controllers/correspondence_controller_spec.rb, spec/jobs/email_correspondence_job_spec.rb, spec/models/correspondence_spec.rb
- Following refactor of FeedbackJob and FeedbackController
- Made equivalent changes here to be consistent
- Save to DB before calling EmailCorrespondenceJob
- Retrieve from DB inside Job
- Increase test coverage of Job and Controller
- I am not sure whether to go with EmailCorrespondenceJob or CorrespondenceJob (we should use the same approach for both Feedback and Correspondence though).
- I will implement the necessary changes once we've agreed on a strategy, before this gets merged.
=> Make correspondence consistent with Feedback

README.md, app/mailers/application_mailer.rb, app/mailers/correspondence_mailer.rb, app/mailers/feedback_mailer.rb, config/application.rb, config/environment.rb, config/environments/development.rb, config/environments/production.rb, config/environments/test.rb, config/initializers/config.rb, config/settings.yml, spec/jobs/email_correspondence_job_spec.rb, spec/mailers/correspondence_mailer_spec.rb, spec/mailers/feedback_mailer_spec.rb, spec/models/correspondence_spec.rb, spec/models/feedback_spec.rb
Move env vars into `settings.yml` so that they aren't required to run the app. Instead, we have acceptable defaults for development in `settings.yml` and can override them with env vars (e.g. SETTINGS__GENERAL_ENQUIRIES_EMAIL) in the deployment environments.
This PR will require a matching change to ministryofjustice/correspondence-tool-deploy which has yet to be done.
=> Clean up configs using env vars

config/environments/production.rb, run.sh
This fixes the lack of application logs in the production environments by ensuring logging goes to STDOUT. It has been tested in dev by building and deploying this branch in Jenkins.
=> CT-168 always log to stdout in production

app/controllers/feedback_controller.rb, app/jobs/email_feedback_job.rb, app/models/feedback.rb, config/initializers/feedback_logger.rb, db/migrate/20161027142803_create_feedback.rb, db/schema.rb, spec/controllers/feedback_controller_spec.rb, spec/jobs/email_feedback_job_spec.rb, spec/models/feedback_spec.rb
This PR builds ontop of #86, which should be merged first before this one.
This change reworks the original work done to get the feedback into the DB to take advantage of JSON-fields for feedback responses so that we can be flexible and change what feedback we ask for without changing the DB schema.
=> CT-153 save all feedback to db

app/controllers/feedback_controller.rb, app/views/feedback/confirmation.html.slim, config/locales/en.yml, spec/controllers/feedback_controller_spec.rb, spec/features/send_feedback_spec.rb
Two for the price of one:
https://dsdmoj.atlassian.net/browse/CT-188
and...
https://dsdmoj.atlassian.net/browse/CT-166
Confirm that feedback has been submitted and take the user back to the MoJ homepage upon completion, rather than back to the webform, which confuses some people (they think that they need to do it all again).
=> CT-188  Clarify successful transactions

Gemfile, Gemfile.lock
Not certain why but in certain circumstances ruby seems to lose it's
link to the readline dylib causing byebug to raise errors when being
required, possibly as a result of a 'brew update'. The fix in this
commit is mentioned here:
https://github.com/deivid-rodriguez/byebug/issues/289
The alternative seems to be to recompile ruby.
=> Fix byebug error

app/models/correspondence.rb, app/views/correspondence/new.html.slim, config/locales/en.yml, config/settings.yml, spec/controllers/correspondence_controller_spec.rb, spec/factories/correspondence.rb, spec/features/send_correspondence_spec.rb, spec/mailers/correspondence_mailer_spec.rb, spec/models/correspondence_spec.rb
Replace the category radio buttons with a free text area.
https://dsdmoj.atlassian.net/secure/RapidBoard.jspa?rapidView=25&projectKey=CT&view=detail&selectedIssue=CT-266
Allow users to enter in their own topic to see if we get more useful topics from them.
=> CT-266 replace topic with text field

app/assets/stylesheets/email.css, app/assets/stylesheets/moj/_govuk_overrides.scss, app/assets/stylesheets/moj/_typography.scss, app/controllers/correspondence_controller.rb, app/jobs/email_confirmation_job.rb, app/mailers/confirmation_mailer.rb, app/views/confirmation_mailer/new_confirmation.html.slim, app/views/correspondence/confirmation.html.slim, config/locales/en.yml, spec/controllers/correspondence_controller_spec.rb, spec/factories/correspondence.rb, spec/features/send_correspondence_spec.rb, spec/features/send_feedback_spec.rb, spec/jobs/email_confirmation_job_spec.rb, spec/mailers/confirmation_mailer_spec.rb, spec/mailers/previews/confirmation_mailer_preview.rb
https://dsdmoj.atlassian.net/browse/CT-163
Confirm submission of the webform, by emailing the user.
Additionally
Tests fixed:
* If you try to add more than 60 chars in a feature test, only 60 are accepted, the model validations do not kick in, but the value stored in the DB is not the same as the value we tried to input - FIXED
* In about 2.6% of test runs, the correspondence factory will generate a topic which fails length validation - FIXED
Tests / coverage added:
* MoJ homepage links on confirmation pages are present and correct
* When user attempts to input a topic of more than 60 chars, the input field won't allow it
=> CT-163 Acknowledge submission of correspondence

app/views/correspondence/search.html.slim, spec/features/send_correspondence_spec.rb, spec/site_prism/pages/correspondence/search_page.rb
https://dsdmoj.atlassian.net/browse/CT-496
This adds 4 new events It creates a category called
'External link - Results'. The first three results
are unique events by tagging their order in the results,
title and link.
The last event is generic and records how many people
clicked on the the 'More results' link
=> CT-496 Add GA Tracking to the GOVUK API results

Gemfile.lock
https://dsdmoj.atlassian.net/browse/CT-567
Code Climate identified a security flaw with a gem our service
was using.
Code Climate Notice:
Advisory: CVE-2017-5946
URL: rubyzip/rubyzip#315
Solution: upgrade to >= 1.2.1
=> CT-567 Update rubyzip

Gemfile, Gemfile.lock, app/controllers/correspondence_controller.rb, app/models/correspondence.rb, app/services/correspondence_creator.rb, app/views/confirmation_mailer/new_confirmation.html.slim, app/views/correspondence/already_authenticated.html.slim, app/views/correspondence/authenticate.html.slim, config/locales/en.yml, config/routes.rb, config/settings.yml, db/migrate/20170412140235_add_authenticated_and_uuid_to_correspondence.rb, db/schema.rb, lib/tasks/sidekiq.rake, spec/controllers/correspondence_controller_spec.rb, spec/factories/correspondence.rb, spec/features/correspondence_authentication_spec.rb, spec/features/send_correspondence_spec.rb, spec/mailers/confirmation_mailer_spec.rb, spec/models/correspondence_spec.rb, spec/services/correspondence_creator_spec.rb
This PR adds an extra step to the process of a member of the public submitting
a correspondence item.  When the item is created, a mail with a URL comprising the
item's uuid is sent to the specified email address, and the item is not consiered
authenticated until the user has clicked on the link in the email.
=> CT-605 Authenticate incoming correspondence items

Gemfile.lock
Advisory: CVE-2016-4658
URL: sparklemotion/nokogiri#1615
Solution: upgrade to >= 1.7.1
=> CT-673 Update Nokogiri gem security

app/controllers/correspondence_controller.rb, config/routes.rb, config/settings.yml, spec/controllers/correspondence_controller_spec.rb, spec/views/correspondence/confirmation_html_slim_spec.rb
This PR fixes a bug whereby reloading the confirmation page would re-submit the correspondence request.
=> CT-655 prevent dupe submission

Gemfile.lock
It would appear that the author of Parser removed a version of the Gem
that we were using. This caused the smoke tests to fail twice over the
weekend.
Known vulnerability found
CVE-2018-8048
Moderate severity
Loofah allows non-whitelisted attributes to be present in sanitized
output when input with specially-crafted HTML fragments
Gemfile.lock update suggested:
loofah ~> 2.2.1
Always verify the validity and compatibility of suggestions with your codebase.
flavorjones/loofah#144
=> Fix smoke tests and address security vulnerablity

Dockerfile
When compiling assets you need to specify which rails env those assets will be used in else it defaults to develop. In develop environment, it does not minify or concatenate the assets that the service is using.
=> Fixes assets not minifying

app/controllers/correspondence_controller.rb, build.sh, config/routes.rb, spec/controllers/correspondence_controller_spec.rb
We discovered a potential leak where the confirmation page used the sequential Correspondence.id as the URL parameter for the confirmation page when sending a contact email to MOJ. If the user started decrementing the integer in the URL, they could browse the email addresses of previous users. This PR changes the redirect from create, the confirmation route and the confirmation controller action to use the existing UUID field (used for the email -> authenticate step) instead of the ID in order to display the confirmation code. This has loads of entropy and is acceptably secure for this purpose.
=> CT-2867 users can no longer inspect emails from previous users

Gemfile, Gemfile.lock
https://github.com/advisories/GHSA-j6w9-fv6q-3q52
CVE-2020-8184
high severity
Vulnerable versions: < 2.1.4
Patched version: 2.1.4
A reliance on cookies without validation/integrity check security vulnerability exists in rack < 2.2.3, rack < 2.1.4 that makes it is possible for an attacker to forge a secure or host-only cookie prefix.
Upgraded sidekiq and other dependencies to allow this update
=> CT-2688 Upgrade rack to version 2.2.3

app/assets/stylesheets/application.css.scss, app/assets/stylesheets/moj/_alert_banner.scss, app/views/layouts/_alert_banner.html.slim, app/views/layouts/application.html.slim, config/locales/en.yml
A reusable banner with a message notifying users of a delayed response. Didn't add tests as it's temporary (hopefully!) - but can consider.
https://dsdmoj.atlassian.net/browse/CT-3118
n/a
All pages should have the banner on top
=> CT-3118 Add reusable alert banner for covid19

app/assets/stylesheets/moj/_govuk_overrides.scss
Make the Start now link keep text white even when pressed.
Before: 
After: 
https://dsdmoj.atlassian.net/browse/CT-3208
n/a
Click on start now and keep the mouse button down, or tab to it. The text should stay white instead of blue, so keeping AA/AAA contrast. https://staging.contact-moj.service.justice.gov.uk/
=> CT-3208 Add more specificity to link to keep it white

app/views/pages/accessibility.html.slim, config/locales/en.yml
Use page titles that make more sense
BEFORE: =====
Accessibility statement:
Confirm Email page:
Message sent page: 
AFTER: ====
Accessibility statement title:
Confirm Email page:
Message sent page
https://dsdmoj.atlassian.net/browse/CT-2767
n/a
submit a question then check the page titles when before and after confirming Email, they should make sense.
https://development.contact-moj.service.justice.gov.uk/
=> CT-2767 use clearer page titles

config/kubernetes/production/cronjob-delete-old-ecr-images.yaml
Increase number of left over master images to 25 for safety against losing the one on production (if 10 master images are built, that are not on prod, then the prod one would be deleted).- so reduce risk - make it 25
https://dsdmoj.atlassian.net/browse/CT-3303
n/a
n/a - once on production, we should gradually see master images increase to 25. this can be tested by querying the images using this command: aws ecr list-images --region eu-west-2 --repository-name [repo name]  --query 'imageIds[*]' --output json
=> CT-3303 Increase master images to keep

config/locales/en.yml
Restore original banner before RDS upgrade
was
is
(part of RDS upgrade) https://dsdmoj.atlassian.net/browse/CT-3414
as part of production with sql client update - post RDS upgrade
should see banner from before 5th feb
=> CT-3414 restore original banner

Gemfile, Gemfile.lock, spec/rails_helper.rb
Replaces Poltergeist with `webdrivers` and chrome as [poltergeist is deprecated](https://github.com/teampoltergeist/poltergeist)
[CT-3642](https://dsdmoj.atlassian.net/browse/CT-3642)
if you haven't already run `rails db:test:prepare`
Then run `bundle exec rspec` to run the tests locally.
=> CT-3642 Replace poltergeist with webdriver/chromedriver

app/views/layouts/application.html.slim
Remove covid banner and hide Alert banner for now just in case we need to reuse
before:
after:
https://dsdmoj.atlassian.net/browse/CT-4094
n/a
Try to find the banner on browser
=> CT-4094 Hide covid alert banner

app/controllers/feedback_controller.rb, app/views/pages/accessibility.html.slim, config/locales/en.yml, config/routes.rb, spec/features/send_feedback_spec.rb
This is an attempt to try to reduce spam received through the feedback form. We are removing the links from the accessibility page as this form doesn't belong here, but we are leaving the link in the remaining places.
Renamed the URL (as the spam bot might reuse the old URL).
Also fixed a minor typo I found in the copy.
Note: we might need to iterate on this if we find out spam is still received, but for now this is a first step.
Before:
After:
https://dsdmoj.atlassian.net/browse/CT-4199
1. The link to the feedback form is no longer in the accessibility page.
2. The feedback form can still be accessed from the other places.
3. Feedback form works as before, despite the URL being changed.
=> CT-4199 Remove feedback links from accessibility page

.circleci/config.yml, Dockerfile, Gemfile.lock
`--path` and `--without` are deprecated
Using `deployment` stops any changes being made to `Gemfile.lock` and installs gems to `vendor/bundle`
`without` stops gems from the specified groups being installed. We don't need development and test dependencies installed in production.
=> Update bundler and remove deprecated settings

app/controllers/heartbeat_controller.rb, config/kubernetes/development/ingress-live.yaml, config/kubernetes/production/ingress-live.yaml, config/kubernetes/staging/ingress-live.yaml, spec/controllers/heartbeat_controller_spec.rb
When the healtcheck fails, report the errors to Sentry. Also changes the status from 502 to 503.
Also updates ingress so the failing healthcheck page will be rendered. Currently 5xx errors are rendered from a custom error page outside of the application
=> Send healthcheck error to sentry

app/controllers/heartbeat_controller.rb, config/kubernetes/development/ingress-live.yaml, config/kubernetes/production/ingress-live.yaml, config/kubernetes/staging/ingress-live.yaml, spec/controllers/heartbeat_controller_spec.rb
Value sent to Sentry needs to be a string.
Setting nginx.ingress.kubernetes.io/custom-http-errors to "418" (https://runbooks.cloud-platform.service.justice.gov.uk/custom-default-backend.html#use-platform-level-error-page) didn't work, so trying explicitly allowing the 503 error.
=> Fix heartbeat sentry logging

app/controllers/heartbeat_controller.rb, spec/controllers/heartbeat_controller_spec.rb
Using `ActiveRecord::Base.connection.active?` seems to be flaky in Rails 7, so trying a simple Select statement instead.
=> Change db test

.github/workflows/test.yml
Upgrade path from 12 -> 13.14 -> 16.2
https://dsdmoj.atlassian.net/jira/software/c/projects/CDPT/boards/1152?selectedIssue=CDPT-1820
=> Test database upgrade

config/kubernetes/production/ingress-live.yaml
Enables [modsec](https://user-guide.cloud-platform.service.justice.gov.uk/documentation/networking/modsecurity.html) in detection mode on production so we can be aware of any issues and evaluate if more protection is required.
=> CDPT-1952 Enable modsec detection mode on production

app/controllers/correspondence_controller.rb, spec/controllers/correspondence_controller_spec.rb
Users have to confirm their email address by clicking a link in an email sent to their address. 
There is a bug that means an email is sent every time the link it clicked, or the page refreshed.
This change checks if the correspondence has already been authenticated so that the correspondence email will only be sent once.
=> CDPT-2483 Check if correspondence already authenticated

app/controllers/cookies_controller.rb, app/helpers/analytics_helper.rb, app/javascript/application.js, app/javascript/cookie_banner.js, app/models/consent_cookie.rb, app/views/cookies/show.html.erb, app/views/layouts/_cookie_banner.html.erb, app/views/layouts/_cookie_banner_confirmation.html.erb, app/views/layouts/_gtm.html.erb, app/views/layouts/_gtm_noscript.html.erb, app/views/layouts/application.html.erb, config/locales/en.yml, config/routes.rb, spec/controllers/cookies_controller_spec.rb, spec/features/cookie_banner_spec.rb, spec/features/cookie_page_spec.rb
Adds a cookie banner to Contact MoJ service. 
~~Found a small bug with some of the javascript when working on this, which I'll fix in another PR. This bug prevents JS from running on pages without the max character count.~~ fix now in main
~~The link to 'View cookies' currently does not work because the cookie page needs to be created. That PR will be based off this one.~~ Cookie page PR has been merged into this one so this is now a standalone piece of work.
https://dsdmoj.atlassian.net/browse/CDPT-2449
~~Will need to be merged together with the cookie page.~~ Cookie page added to this PR
For UI testing:
- open a browser on the homepage
- observe banner
- accept or reject cookies
- observer confirmation banner
- click on hide and observe hide behaviour
- clear cookies in the dev tools …
=> CDPT-2449: Cookie consent banner

app/views/correspondence/_feedback.html.erb, app/views/errors/internal_error.html.erb, app/views/errors/not_found.html.erb, app/views/layouts/application.html.erb, app/views/pages/accessibility.html.erb, config/locales/en.yml, spec/features/send_correspondence_spec.rb, spec/features/send_feedback_spec.rb, spec/views/pages/accessibility.html.erb_spec.rb
Update Accessibility statement. 
Add new feedback link at end of service, and in govuk phase banner under header.
Also have updated site to reference new support email.
https://dsdmoj.atlassian.net/browse/CDPT-2642
https://dsdmoj.atlassian.net/browse/CDPT-2646
none
- Visit pages, check content and links work as expected
=> CDPT-2642, CDPT-2646: Update accessibility statement and add new feedback link
